# Generated by Django 3.0.8 on 2020-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='gambar')),
                ('nama_barang', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alamat', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
