# Generated by Django 3.0.8 on 2020-07-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='alamat',
        ),
    ]
