# Generated by Django 3.0.8 on 2020-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_app', '0002_remove_barang_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.CharField(choices=[('baju', 'baju'), ('celana', 'celana'), ('musik', 'musik')], default=True, max_length=50),
            preserve_default=False,
        ),
    ]
