# Generated by Django 3.0.8 on 2020-07-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko_app', '0003_barang_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gambar')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko_app.Barang')),
            ],
        ),
    ]
