# Generated by Django 3.0.8 on 2020-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_app', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
